# Generated by Django 4.1.2 on 2022-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200)),
                ('StudentClass', models.CharField(max_length=200)),
                ('AdmissionFee', models.IntegerField()),
                ('PaidAmount', models.IntegerField()),
                ('BalanceAmount', models.IntegerField()),
                ('DocRefCode', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=200)),
                ('AttendanceDate', models.CharField(max_length=200)),
                ('SmsStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=200)),
                ('TotalFee', models.IntegerField()),
                ('PaidAmount', models.IntegerField()),
                ('DueAmount', models.IntegerField()),
                ('FeeStructure', models.CharField(max_length=200)),
                ('VoucherMonth', models.CharField(max_length=200)),
                ('PostStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('AcademicYear', models.CharField(max_length=200)),
                ('AcademicClass', models.CharField(max_length=200)),
                ('School', models.CharField(max_length=200)),
                ('AdmissionDate', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=200)),
                ('PostStatus', models.CharField(max_length=200)),
            ],
        ),
    ]
