# Generated by Django 4.1.2 on 2022-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_voucher_poststatus_remove_voucher_studentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='AcademicClass',
        ),
        migrations.RemoveField(
            model_name='student',
            name='AcademicYear',
        ),
        migrations.RemoveField(
            model_name='student',
            name='AdmissionDate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='School',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='StudentId',
        ),
        migrations.AddField(
            model_name='student',
            name='Acadamic_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='division_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='division_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='partner_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='standard_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='standard_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
