# Generated by Django 4.1.2 on 2022-10-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_student_academicclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='offline_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='received_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
