# Generated by Django 4.1.2 on 2022-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_voucher_offline_status_voucher_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='journal_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
