# Generated by Django 4.1.2 on 2022-11-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_voucher_journal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='received_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
