# Generated by Django 4.1.2 on 2022-11-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_voucher_received_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='AdmissionFee',
            new_name='admission_fee',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='BalanceAmount',
            new_name='balance_amount',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='DocRefCode',
            new_name='document_referance',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='PaidAmount',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='StudentClass',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='StudentName',
            new_name='student_name',
        ),
    ]
