# Generated by Django 4.1.2 on 2022-11-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_admissionfee_admission_admission_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='AttendanceDate',
            new_name='attendance_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='SmsStatus',
            new_name='sms_status',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='StudentId',
            new_name='student_id',
        ),
    ]
